name: Task 15

on:
  workflow_dispatch:

jobs:
  deploy-sim:
    runs-on: ubuntu-latest

    environment:
        name: production

    steps:
      - name: Print message
        run: echo "Waiting for approval"

      - name: Accepted
        run: echo "Deployment started"  