name: Task 11

on: 
  pull_request:
    branches:
      - develop

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR number
        run: echo "PR number = ${{ github.event.pull_request.number }}"
      - name: Print Source branch
        run: echo "Source branch = ${{ github.head_ref }}"
      - name: Print target branch
        run: echo "Target branch = ${{ github.base_ref }}"
