name: Task 4

on:
    workflow_dispatch:

jobs:
    secret-demo:

        runs-on: ubuntu-latest

        steps:

            - name: Print a message
              run: echo "API key received"
            
            - name: Length of key
              env:
                API_KEY: ${{ secrets.API_KEY }}
              run: |
                echo "Length: ${#API_KEY}"