name: Task 2

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                options:
                    - dev
                    - stag
                    - prod
                required: true
            debug:
                type: boolean
                default: false

jobs:
    input-demo:

        runs-on: ubuntu-latest

        steps:

            - name: Print Environment
              run: echo "Environment = ${{ inputs.environment }}"
            
            - name: Debug info
              
              run: |
                if [ ${{inputs.debug}} == 'true' ] 
                then
                    echo "Debugging Enabled"
                else
                    echo "Debugging disabled"
                fi