name: Task 14

on:
  workflow_dispatch:

jobs:
  timeout-demo:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Output and Sleep
        run: |
          echo "Job Started"
          sleep 90
